configure: revert palm change to force i386 HOST on x86_64
-otherwise build for qemux86-64 fails with:
| make[1]: *** Waiting for unfinished jobs....
| ../../include/QtCore/../../../git/src/corelib/arch/qatomic_i386.h: Assembler messages:
| ../../include/QtCore/../../../git/src/corelib/arch/qatomic_i386.h:177: Error: incorrect register `%rbp' used with `l' suffix
| ../../include/QtCore/../../../git/src/corelib/arch/qatomic_i386.h:177: Error: incorrect register `%rbp' used with `l' suffix
| ../../include/QtCore/../../../git/src/corelib/arch/qatomic_i386.h: Assembler messages:
| ../../include/QtCore/../../../git/src/corelib/arch/qatomic_i386.h:177: Error: incorrect register `%rbp' used with `l' suffix
| make[1]: *** [.obj/release-shared/qglobal.o] Error 1

-build native qmake-palm on 64-bit host instead of 32-bit executable

Open-webOS-DCO-1.0-Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Open-webOS-DCO-1.0-Signed-off-by: Weiwen Zhao <panda.hust@gmail.com>